Added docstrings, Typehinting and isinstance for checking the type
thenithinbalaji/pyrandtoys pull request #4
Opened 2022-03-07 18:11 UTC by Dhravya

2022-03-07 18:40 UTC, thenithinbalaji requested changes

2022-03-07 18:40 UTC, thenithinbalaji commented on pyrandtoys/functions.py
> +    if isinstance(list, list):
Must be comparing str right?
```
if isinstance(list, str):
        temp = []
        temp.append(list)
        list = temp
```

2022-03-07 18:51 UTC, Dhravya commented on pyrandtoys/functions.py
> +    if isinstance(list, list):
Oh, sorry, my bad

2022-03-07 22:21 UTC, TrapinchO commented on pyrandtoys/functions.py
> +    if isinstance(list, list):
maybe change it to this?
```python
if isinstance(list, str):
    list = [list]
```

2022-03-08 12:25 UTC, Dhravya commented
Hi there, changes have been done, you can merge now

2022-03-08 16:11 UTC, thenithinbalaji approved these changes
LGTM 👍

2022-03-08 16:13 UTC, merged